[profile.default]
src = "src"
out = "out"
script = "script"
solc = "0.8.24"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
libs = ["../../contracts/lib"]
remappings = ["forge-std/=../../contracts/lib/forge-std/src/"]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
